### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by vimal-hoh** [Kaltsoon/Angular-Node-Token-Auth#1]
module.js:340
    throw err;
          ^
Error: Cannot find module '/home/pooja/vimal/programs/Angular-Node-Token-Auth/start'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
pooja@admin-ThinkPad-T61:~/vimal/programs/Angular-Node-Token-Auth$ node bin/www
/home/pooja/vimal/programs/Angular-Node-Token-Auth/app/services/auth.js:42
module.exports = { createTokenForUser, verifyAuthentication, verifyIsSignedInU
                                     ^
SyntaxError: Unexpected token ,
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pooja/vimal/programs/Angular-Node-Token-Auth/routes/users.js:3:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by Kaltsoon** [comment]
Try installing the latest version of Node. It seems that some ES6 syntax features are causing trouble.
